apiVersion: v1
kind: ConfigMap
metadata:
  name: mr-config
  namespace: mapreduce
data:
  MANAGER_PORT: "8080"
  MINIO_BUCKET: "mr-bucket"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: mapreduce
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin