apiVersion: v1
kind: Namespace
metadata:
  name: mapreduce
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mr-manager-sa
  namespace: mapreduce
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mr-worker-sa
  namespace: mapreduce